"""
output_writer.py – Persist the scorecard in Markdown, JSON, and HTML formats.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, BaseLoader

from agent.runner import ScorecardResult

# ─── HTML template ────────────────────────────────────────────────────────────
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>AI Terms Scorecard – {{ result.product_name }}</title>
<style>
  :root { --accent: #0078d4; --good: #107c10; --warn: #ff8c00; --bad: #a4262c; }
  body { font-family: "Segoe UI", system-ui, sans-serif; max-width: 900px;
         margin: 2rem auto; padding: 0 1rem; color: #1b1b1b; }
  h1 { color: var(--accent); border-bottom: 2px solid var(--accent); padding-bottom: .4rem; }
  h2 { color: #333; margin-top: 2rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #ddd; padding: .6rem .9rem; text-align: left; vertical-align: top; }
  th { background: #f0f4f8; }
  .score-high  { color: var(--good); font-weight: 700; }
  .score-mid   { color: var(--warn); font-weight: 700; }
  .score-low   { color: var(--bad);  font-weight: 700; }
  .badge { display:inline-block; padding:.2rem .6rem; border-radius:.4rem;
           font-size:.85rem; font-weight:600; }
  .badge-high { background:#dff6dd; color:var(--good); }
  .badge-mid  { background:#fff4ce; color:var(--warn); }
  .badge-low  { background:#fde7e9; color:var(--bad); }
  pre { background:#f6f8fa; padding:1rem; border-radius:.4rem; overflow-x:auto; }
  footer { margin-top:3rem; font-size:.8rem; color:#666; }
</style>
</head>
<body>
<h1>AI Terms Scorecard</h1>
<p><strong>Product:</strong> {{ result.product_name }}<br/>
<strong>Vendor:</strong> {{ result.vendor }}<br/>
<strong>Generated:</strong> {{ timestamp }}</p>

{% if result.structured %}
<h2>Score Summary</h2>
<table>
  <thead><tr><th>Criterion</th><th>Score</th><th>Notes</th></tr></thead>
  <tbody>
  {% for key, val in result.structured.items() if key != "overall" and key != "metadata" %}
    {% set score = val.score if val is mapping else val %}
    {% set notes = val.notes if val is mapping else "" %}
    <tr>
      <td>{{ key | replace("_", " ") | title }}</td>
      <td>
        {% if score | string | float(-1) >= 3.5 %}
          <span class="badge badge-high">{{ score }}</span>
        {% elif score | string | float(-1) >= 2 %}
          <span class="badge badge-mid">{{ score }}</span>
        {% else %}
          <span class="badge badge-low">{{ score }}</span>
        {% endif %}
      </td>
      <td>{{ notes }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% if result.structured.overall is defined %}
<p><strong>Overall Score:</strong> {{ result.structured.overall }}</p>
{% endif %}
{% endif %}

<h2>Full Report</h2>
<div id="report">
{{ md_as_html | safe }}
</div>

<footer>
  Generated by AITermsScore &bull; Run ID: {{ result.run_id }} &bull; Thread: {{ result.thread_id }}
</footer>
</body>
</html>
"""


def _md_to_simple_html(md: str) -> str:
    """Minimal Markdown → HTML conversion (headers, bold, code blocks, links)."""
    try:
        import markdown as md_lib  # type: ignore
        return md_lib.markdown(md, extensions=["tables", "fenced_code"])
    except ImportError:
        # Fallback: wrap in <pre>
        escaped = md.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"<pre>{escaped}</pre>"


def _safe_filename(name: str) -> str:
    return re.sub(r"[^\w\-]", "_", name).lower()


def write_outputs(result: ScorecardResult, output_dir: Path) -> dict[str, Path]:
    """
    Write Markdown, JSON, and HTML scorecard files.
    Returns a dict of format → absolute Path.
    """
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    stem = f"{ts}_{_safe_filename(result.product_name)}"
    paths: dict[str, Path] = {}

    # ── Markdown ──────────────────────────────────────────────────────────────
    md_path = output_dir / f"{stem}.md"
    header = (
        f"# AI Terms Scorecard – {result.product_name}\n\n"
        f"**Vendor:** {result.vendor}  \n"
        f"**Generated:** {ts}  \n"
        f"**Run ID:** {result.run_id}  \n\n---\n\n"
    )
    md_path.write_text(header + result.raw_markdown, encoding="utf-8")
    paths["markdown"] = md_path

    # ── JSON ──────────────────────────────────────────────────────────────────
    json_path = output_dir / f"{stem}.json"
    structured = result.structured if isinstance(result.structured, dict) else {}
    payload = {
        "product_name": result.product_name,
        "vendor": result.vendor,
        "generated_utc": ts,
        "run_id": result.run_id,
        "thread_id": result.thread_id,
        "scores": structured,
        "raw_markdown": result.raw_markdown,
    }
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    paths["json"] = json_path

    # ── HTML ──────────────────────────────────────────────────────────────────
    html_path = output_dir / f"{stem}.html"
    env = Environment(loader=BaseLoader())  # type: ignore[call-arg]
    template = env.from_string(_HTML_TEMPLATE)
    # Ensure structured is always a dict for the Jinja2 template
    render_result = result
    if not isinstance(result.structured, dict):
        from dataclasses import replace
        render_result = replace(result, structured={})
    html_content = template.render(
        result=render_result,
        timestamp=ts,
        md_as_html=_md_to_simple_html(result.raw_markdown),
    )
    html_path.write_text(html_content, encoding="utf-8")
    paths["html"] = html_path

    return paths
